# The interval in seconds indicates how often this tool synchronizes with the remote.
# 'check_interval == 0' means run this tool only once and then exit.
check_interval: 30

records:
  - type: A
    name: case1.dns-syncer-test
    content: 8.8.8.8
    comment: 'DNS Syncer, google dns'
    op: create
    backends:
      - provider: cloudflare-1
        zones:
          - example-au.org


  - type: A
    name: case2.dns-syncer-test
    content: 8.8.8.9
    comment: 'A test address'
    op: create
    backends:
      - provider: "cloudflare-1"
        params:
          - name: "proxied"
            value: "true"
        zones:
          - "example-au.org"

  - type: AAAA
    name: case1.dns-syncer-test
    comment: test3 only
    op: create
    backends:
      - provider: cloudflare-1
        zones:
          - example-au.org
          - example-uk.org
      - provider: cloudflare-2
        zones:
          - example-us.org



providers:
  - name: cloudflare-1
    type: cloudflare
    authentication:
      type: api_token
      value: AABBCCDDEEFFGG
  - name: cloudflare-2
    type: cloudflare
    authentication:
      type: api_key
      value:
        email: test@example.com
        key: AABBCCDDEEFFGG

fetchers:
  - name: http_fetcher-1
    type: http_fetcher
    alive: 10

public_ip_fecher: http_fetcher-1