# The interval in seconds indicates how often this tool synchronizes with the remote.
# 'check_interval == 0' means run this tool only once and then exit.
check_interval: 30

records:
  - type: A
    name: case1.dns-syncer-test
    content: 8.8.8.8
    comment: 'DNS Syncer, google dns'
    op: create
    labels:
      - key: proxied
        val: true
    backends:
      - provider: cloudflare-1
        zone: example-au.org

  - type: A
    name: case2.dns-syncer-test
    comment: test2 only
    op: purge
    backends:
      - provider: cloudflare-1
        zone: example-au.org

  - type: AAAA
    name: case1.dns-syncer-test
    comment: test3 only
    op: create
    backends:
      - provider: cloudflare-1
        zone: example-au.org
      - provider: cloudflare-2
        zone: example-us.org

providers:
  - name: cloudflare-1
    type: cloudflare
    authentication:
      type: api_token
      value: AABBCCDDEEFFGG
  - name: cloudflare-2
    type: cloudflare
    authentication:
      type: api_key
      value:
        email: test@example.com
        key: AABBCCDDEEFFGG

fetchers:
  - name: http_fetcher-1
    type: http_fetcher
    alive: 10
    sources:
      - name: cloudflare

public_ip_fecher: http_fetcher-1