# The interval in seconds indicates how often this tool synchronizes with the remote.
# 'check_interval == 0' means run this tool only once and then exit.
check_interval: 30
providers:
  - name: cloudflare-1
    type: cloudflare
    authentication:
      api_token: AABBCCDDEEFFGG
    zones:
      - id: "112233445566"
        records:
          - type: A
            name: test1.example-au.org
            proxied: true
            content: 8.8.8.8
            comment: 'DNS Syncer, google dns'
            op: create
          - type: A
            proxied: false
            name: test2.example-au.org
            comment: test2 only
            op: overwrite
            # If "content" field is not specified, the default is to use the 
            #public IP address obtained from 'https://1.1.1.1/cdn-cgi/trace' on Cloudflare.

fetchers:
  - name: http_fetcher-1
    type: http_fetcher
    alive: 10
    sources:
      - name: cloudflare

public_ip_fecher: http_fetcher-1